import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {gunzipSync} from 'node:zlib';import {DEFAULT,PRESETS,evaluate,quantile,powerMean,kernelOf,matchPreset} from '../dist/model.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),data=path.join(root,'dist/data'),read=n=>JSON.parse(fs.readFileSync(path.join(data,n),'utf8'));
let checks=0,seed=20260912;const random=()=>((seed=(1664525*seed+1013904223)>>>0)/4294967296);const close=(a,b,tol=2e-7)=>{checks++;if(!Number.isFinite(a)||!Number.isFinite(b)){assert.ok(a===b||Number.isNaN(a)&&Number.isNaN(b));return;}assert.ok(Math.abs(a-b)<=tol*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`);};
function reference(c,m,s){const atoms=c.map((v,i)=>[v,m[i]]).filter(x=>x[1]>0).sort((a,b)=>a[0]-b[0]),W=atoms.reduce((a,x)=>a+x[1],0),K=kernelOf(s);let sum=0,cum=0,qt=Infinity;for(const [v,w]of atoms){const overlap=Math.max(0,cum+w-Math.max(cum,s.lower*W));sum+=overlap*K(v);cum+=w;if(qt===Infinity&&cum>=s.rank)qt=v;}let z=W**s.a*((s.tau<1?(1-s.tau)*sum/(W*(1-s.lower)):0)+(s.tau>0?s.tau*qt:0));return s.b===0?(z>=s.threshold?1:0):z**s.b;}
for(const p of PRESETS)assert.equal(matchPreset(p.params)?.id,p.id);
for(let i=0;i<600;i++){const c=Array.from({length:7+Math.floor(random()*35)},()=>.05+random()*50),m=c.map(()=>.1+random()*3),s={...DEFAULT,kernel:i%2?'exponential':'identity',a:random(),lower:random()*.9,b:1};if(s.kernel==='identity'){s.tau=random();s.rank=random()*m.reduce((a,b)=>a+b,0);}close(evaluate(c,m,s),reference(c,m,s),1e-10);const r=.2+random()*5;close(quantile(c,m,r),c.map((v,j)=>[v,m[j]]).sort((a,b)=>a[0]-b[0]).find((x,j,arr)=>arr.slice(0,j+1).reduce((a,b)=>a+b[1],0)>=r)?.[0]??Infinity);}
close(evaluate([1,2],[1,1],{...DEFAULT,kernel:'identity',tau:1,a:0,rank:3}),Infinity);close(quantile([2,2,5],[.5,1.5,1],2),2);close(powerMean([2,18],1),10);close(powerMean([2,18],5),18);close(powerMean([2,18],-5),2);
const net=read('network.json'),allPois=read('pois.json'),meta=read('metadata.json'),N=net.nodes.length;const reports=[];
for(const cat of meta.categories){const pp=allPois.filter(p=>p.category===cat.id),M=pp.length,buffer=gunzipSync(Buffer.concat(read('route-manifest.json').categories[cat.id].parts.map(part=>fs.readFileSync(path.join(root,'dist',part.url))))),d=new Float32Array(buffer.buffer,buffer.byteOffset,buffer.length/4),cached=read(cat.id+'-presets.json');assert.equal(d.length,N*M);const states=PRESETS.filter(p=>p.params.domain==='poi');const masses={};
 for(const p of states){const s=p.params,m=Float64Array.from(pp,q=>s.supply==='one'?1:q.weight);if(s.gamma>0){const G=kernelOf(s,true);for(let j=0;j<M;j++){let D=0;for(let i=0;i<N;i++)if(net.inside[i])D+=G(d[j*N+i]/80);m[j]=D>0?m[j]/D:0;}}masses[p.id]=m;}
 let comparisons=0;for(let trial=0;trial<20;trial++){const idx=Math.floor(random()*net.streets.length),e=net.streets[idx];const samples=[Array.from({length:M},(_,j)=>d[j*N+e.u]/80),Array.from({length:M},(_,j)=>d[j*N+e.v]/80)];if(e.m>200)samples.push(Array.from({length:M},(_,j)=>(Math.min(d[j*N+e.u],d[j*N+e.v])+e.m/2)/80));for(const p of states){const got=powerMean(samples.map(c=>evaluate(c,masses[p.id],p.params)),1);const expected=cached[p.id][idx]??NaN;close(got,expected);comparisons++;}
  const c=samples[0],one=Array(M).fill(1);assert.ok(evaluate(c,one,{...DEFAULT,kernel:'step',radius:20})>=evaluate(c,one,{...DEFAULT,kernel:'step',radius:10}));assert.ok(evaluate(c,one,{...DEFAULT,beta:.2})<=evaluate(c,one,{...DEFAULT,beta:.04}));assert.ok(quantile(c,one,5)>=quantile(c,one,1));checks+=3;
 }reports.push({category:cat.id,comparisons,allFiniteDistances:Array.from(d.subarray(0,1000)).every(Number.isFinite)});console.log(cat.id,comparisons,'real-street comparisons passed');}
const nc=read('centrality.json'),networkPresets=read('network-presets.json');for(let i=0;i<50;i++){const k=Math.floor(random()*net.streets.length),e=net.streets[k];close(networkPresets.N1[k],(nc.meanMetres[e.u]+nc.meanMetres[e.v])/160);close(networkPresets.N2[k],(80/nc.meanMetres[e.u]+80/nc.meanMetres[e.v])/2);close(networkPresets.N4[k],nc.betweenness[k]);}
assert.equal(new Set(meta.categories.map(c=>read(c.id+'-presets.json').G1.slice(0,50).join(','))).size,5);
const report={status:'passed',seed:20260912,checks,mathematicalFixtures:600,canonicalNameChecks:17,realStreetComparisons:1300,networkMappingComparisons:150,reports,date:new Date().toISOString(),notes:['Independent Python preset surfaces vs common JS evaluator.','Real-data checks sample streets; they do not establish empirical validity.','Graph routing and demand assumptions remain explicit in the guide.']};fs.mkdirSync(path.join(root,'audit'),{recursive:true});fs.writeFileSync(path.join(root,'audit','verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
